//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_DepartamentoEmpleadoPuesto
    {
        public int EmpleadoID { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> PuestoId { get; set; }
        public string DescripcionPuesto { get; set; }
        public Nullable<int> DepartamentoId { get; set; }
        public string DescripcionDepartamento { get; set; }
    }
}
